<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-GAB8185M" failures="1" tests="4" name="testScenarioFour.GiftCardVerify" time="4.129" errors="0" timestamp="2024-09-15T18:01:18 IST" skipped="3">
  <testcase classname="testScenarioFour.GiftCardVerify" name="test21" time="0.000">
    <skipped/>
  </testcase> <!-- test21 -->
  <system-out/>
  <testcase classname="testScenarioFour.GiftCardVerify" name="invokeBrowser" time="4.129">
    <failure message="expected [Gift Cards - Buy Gift Vouchers Online, Gift Vouchers | MakeMyTrip.com] but found [Buy Gift Cards &amp; Vouchers Online from MakeMyTrip]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Gift Cards - Buy Gift Vouchers Online, Gift Vouchers | MakeMyTrip.com] but found [Buy Gift Cards & Vouchers Online from MakeMyTrip]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at baseClasses.PageBase.getTitle(PageBase.java:98)
at pages.Home.clickGiftCard(Home.java:66)
at testScenarioFour.GiftCardVerify.invokeBrowser(GiftCardVerify.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invokeBrowser -->
  <system-out/>
  <testcase classname="testScenarioFour.GiftCardVerify" name="test22" time="0.000">
    <skipped/>
  </testcase> <!-- test22 -->
  <system-out/>
  <testcase classname="testScenarioFour.GiftCardVerify" name="test23" time="0.000">
    <skipped/>
  </testcase> <!-- test23 -->
  <system-out/>
</testsuite> <!-- testScenarioFour.GiftCardVerify -->
